grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

kafka:
  server: "localhost:9092"
  topics:
    telemetry-hubs-v1: "telemetry.hubs.v1"
    telemetry-snapshots-v1: "telemetry.snapshots.v1"
  consumer:
    groups:
      hub-events: "hubEventConsumer"
      snapshot-events: "snapshotEventConsumer"